services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
      - redis
    command: sh -c "php artisan migrate --force && php-fpm"

  nginx:
    image: nginx:1.25
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  echo:
    image: node:20
    container_name: laravel_echo
    working_dir: /var/www
    command: sh -c "rm -f laravel-echo-server.lock && test -f package.json || echo '{\"name\":\"echo\",\"version\":\"1.0.0\"}' > package.json && npm install -g debug@4.3.1 uuid@9 laravel-echo-server && laravel-echo-server start --force"
    volumes:
      - .:/var/www
      - ./laravel-echo-server.json:/var/www/laravel-echo-server.json
      - echo_npm:/root/.npm
    ports:
      - "6001:6001"
    depends_on:
      - app
      - redis

volumes:
  db_data:
  echo_npm:
